name: 'zendesk'
version: '0.0.1'
config-version: 2
require-dbt-version: '>=0.18.0'
on-run-start: "{{ ticket_field_history_columns_warning() }}"

models:
    zendesk:
        +materialized: table
        agent_work_time:
            +materialized: table
        intermediate:
            +materialized: table
        reply_times:
            +materialized: table
        resolution_times:
            +materialized: table
        sla_policy:
            +materialized: table
        ticket_history:
            +materialized: table
        utils:
            +materialized: table

vars:
    zendesk:
        ticket_field_history_columns: [ 'assignee_id', 'status', 'priority' ]
        field_history: "{{ ref('stg_zendesk_ticket_field_history') }}"
        ticket: "{{ ref('stg_zendesk_ticket') }}"
        dbt_utils_dispatch_list:
            - zendesk